### ISSUE TITLE
Custom file icons do not work.

### ISSUE THREAD

**Issue by JustusAdam** [arcticicestudio/northem-dark-atom-ui#2]
I might be misreading the screenshot but are the custom file icons not part of this UI theme? 

They do not work on my versions of atom (just updated to 1.0.3).

Screenshot for convenience

<img width="1440" alt="screen shot 2015-07-29 at 00 56 54" src="https://cloud.githubusercontent.com/assets/5824532/8945987/b878ec2a-358c-11e5-981c-f6dc1a3ed2b2.png">

**Comment by arcticicestudio** [comment]
The file icons aren't part of this theme. I planned to implement these, but I thought it would be better to give the user the possibility to adjust these himself.
The icons on the screenshot are provided by the package [`file-icons`](https://atom.io/packages/file-icons).
I must admit the screenshot is a bit confusing, I will update the README to clarify this.

**Comment by arcticicestudio** [comment]
Added notice in the README.

**Comment by AndrewKTyler** [comment]
I am still having this issue
