### ISSUE TITLE
Deprecated selector in `northem-dark-atom-ui\index.less`

### ISSUE THREAD

**Issue by okonomiyaki3000** [arcticicestudio/northem-dark-atom-ui#8]
In `northem-dark-atom-ui\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
* atom-text-editor[mini], atom-text-editor[mini]::shadow => atom-text-editor[mini], atom-text-editor[mini].editor
* atom-text-editor[mini]:hover, atom-text-editor[mini]::shadow:hover => atom-text-editor[mini]:hover, atom-text-editor[mini].editor:hover
* atom-text-editor[mini] .text, atom-text-editor[mini]::shadow .text, atom-text-editor[mini] .source, atom-text-editor[mini]::shadow .source => atom-text-editor[mini] .text, atom-text-editor[mini].editor .syntax--text, atom-text-editor[mini] .source, atom-text-editor[mini].editor .syntax--source
* atom-text-editor[mini] .placeholder-text, atom-text-editor[mini]::shadow .placeholder-text => atom-text-editor[mini] .placeholder-text, atom-text-editor[mini].editor .placeholder-text
* atom-text-editor[mini] .cursor, atom-text-editor[mini]::shadow .cursor => atom-text-editor[mini] .cursor, atom-text-editor[mini].editor .cursor
* atom-text-editor[mini].is-focused, atom-text-editor[mini].is-focused::shadow => atom-text-editor[mini].is-focused, atom-text-editor[mini].is-focused.editor
* atom-text-editor[mini].is-focused .text, atom-text-editor[mini].is-focused::shadow .text, atom-text-editor[mini].is-focused .source, atom-text-editor[mini].is-focused::shadow .source => atom-text-editor[mini].is-focused .text, atom-text-editor[mini].is-focused.editor .syntax--text, atom-text-editor[mini].is-focused .source, atom-text-editor[mini].is-focused.editor .syntax--source
* atom-text-editor[mini].is-focused:hover, atom-text-editor[mini].is-focused::shadow:hover => atom-text-editor[mini].is-focused:hover, atom-text-editor[mini].is-focused.editor:hover
* atom-text-editor[mini].is-focused .selection .region, atom-text-editor[mini].is-focused::shadow .selection .region => atom-text-editor[mini].is-focused .selection .region, atom-text-editor[mini].is-focused.editor .selection .region
* atom-text-editor .scroll-view, atom-text-editor::shadow .scroll-view, :host .scroll-view => atom-text-editor .scroll-view, atom-text-editor.editor .scroll-view, :host .scroll-view
* atom-panel.modal atom-text-editor[mini], .overlay atom-text-editor[mini], atom-panel.modal atom-text-editor.mini, .overlay atom-text-editor.mini, atom-panel.modal atom-text-editor.mini::shadow, .overlay atom-text-editor.mini::shadow, atom-panel.modal atom-text-editor[mini]::shadow, .overlay atom-text-editor[mini]::shadow => atom-panel.modal atom-text-editor[mini], .overlay atom-text-editor[mini], atom-panel.modal atom-text-editor.mini, .overlay atom-text-editor.mini, atom-panel.modal atom-text-editor.mini.editor, .overlay atom-text-editor.mini.editor, atom-panel.modal atom-text-editor[mini].editor, .overlay atom-text-editor[mini].editor
* atom-panel.modal atom-text-editor[mini] .text, .overlay atom-text-editor[mini] .text, atom-panel.modal atom-text-editor.mini .text, .overlay atom-text-editor.mini .text, atom-panel.modal atom-text-editor.mini::shadow .text, .overlay atom-text-editor.mini::shadow .text, atom-panel.modal atom-text-editor[mini]::shadow .text, .overlay atom-text-editor[mini]::shadow .text => atom-panel.modal atom-text-editor[mini] .text, .overlay atom-text-editor[mini] .text, atom-panel.modal atom-text-editor.mini .text, .overlay atom-text-editor.mini .text, atom-panel.modal atom-text-editor.mini.editor .syntax--text, .overlay atom-text-editor.mini.editor .syntax--text, atom-panel.modal atom-text-editor[mini].editor .syntax--text, .overlay atom-text-editor[mini].editor .syntax--text
* atom-panel.modal atom-text-editor[mini].is-focused:hover, .overlay atom-text-editor[mini].is-focused:hover, atom-panel.modal atom-text-editor.mini.is-focused:hover, .overlay atom-text-editor.mini.is-focused:hover, atom-panel.modal atom-text-editor.mini::shadow.is-focused:hover, .overlay atom-text-editor.mini::shadow.is-focused:hover, atom-panel.modal atom-text-editor[mini]::shadow.is-focused:hover, .overlay atom-text-editor[mini]::shadow.is-focused:hover, atom-panel.modal atom-text-editor[mini]:hover, .overlay atom-text-editor[mini]:hover, atom-panel.modal atom-text-editor.mini:hover, .overlay atom-text-editor.mini:hover, atom-panel.modal atom-text-editor.mini::shadow:hover, .overlay atom-text-editor.mini::shadow:hover, atom-panel.modal atom-text-editor[mini]::shadow:hover, .overlay atom-text-editor[mini]::shadow:hover => atom-panel.modal atom-text-editor[mini].is-focused:hover, .overlay atom-text-editor[mini].is-focused:hover, atom-panel.modal atom-text-editor.mini.is-focused:hover, .overlay atom-text-editor.mini.is-focused:hover, atom-panel.modal atom-text-editor.mini.editor.is-focused:hover, .overlay atom-text-editor.mini.editor.is-focused:hover, atom-panel.modal atom-text-editor[mini].editor.is-focused:hover, .overlay atom-text-editor[mini].editor.is-focused:hover, atom-panel.modal atom-text-editor[mini]:hover, .overlay atom-text-editor[mini]:hover, atom-panel.modal atom-text-editor.mini:hover, .overlay atom-text-editor.mini:hover, atom-panel.modal atom-text-editor.mini.editor:hover, .overlay atom-text-editor.mini.editor:hover, atom-panel.modal atom-text-editor[mini].editor:hover, .overlay atom-text-editor[mini].editor:hover
* .markdown-preview[data-use-github-style] atom-text-editor, .markdown-preview[data-use-github-style] atom-text-editor::shadow => .markdown-preview[data-use-github-style] atom-text-editor, .markdown-preview[data-use-github-style] atom-text-editor.editor
* .markdown-preview[data-use-github-style] atom-text-editor .editor--private span.source, .markdown-preview[data-use-github-style] atom-text-editor::shadow .editor--private span.source => .markdown-preview[data-use-github-style] atom-text-editor .editor--private span.source, .markdown-preview[data-use-github-style] atom-text-editor.editor .editor--private span.syntax--source
* .markdown-preview[data-use-github-style] atom-text-editor, .markdown-preview[data-use-github-style] atom-text-editor::shadow, .markdown-preview[data-use-github-style] code => .markdown-preview[data-use-github-style] atom-text-editor, .markdown-preview[data-use-github-style] atom-text-editor.editor, .markdown-preview[data-use-github-style] code
* .markdown-preview atom-text-editor, .markdown-preview:not([data-use-github-style]) atom-text-editor, .markdown-preview atom-text-editor::shadow, .markdown-preview:not([data-use-github-style]) atom-text-editor::shadow => .markdown-preview atom-text-editor, .markdown-preview:not([data-use-github-style]) atom-text-editor, .markdown-preview atom-text-editor.editor, .markdown-preview:not([data-use-github-style]) atom-text-editor.editor
* .markdown-preview atom-text-editor .editor--private span.source, .markdown-preview:not([data-use-github-style]) atom-text-editor .editor--private span.source, .markdown-preview atom-text-editor::shadow .editor--private span.source, .markdown-preview:not([data-use-github-style]) atom-text-editor::shadow .editor--private span.source => .markdown-preview atom-text-editor .editor--private span.source, .markdown-preview:not([data-use-github-style]) atom-text-editor .editor--private span.source, .markdown-preview atom-text-editor.editor .editor--private span.syntax--source, .markdown-preview:not([data-use-github-style]) atom-text-editor.editor .editor--private span.syntax--source
* .markdown-preview atom-text-editor, .markdown-preview:not([data-use-github-style]) atom-text-editor, .markdown-preview atom-text-editor::shadow, .markdown-preview:not([data-use-github-style]) atom-text-editor::shadow, .markdown-preview code, .markdown-preview:not([data-use-github-style]) code => .markdown-preview atom-text-editor, .markdown-preview:not([data-use-github-style]) atom-text-editor, .markdown-preview atom-text-editor.editor, .markdown-preview:not([data-use-github-style]) atom-text-editor.editor, .markdown-preview code, .markdown-preview:not([data-use-github-style]) code
* atom-text-editor atom-text-editor-minimap::shadow .minimap-visible-area, atom-text-editor::shadow atom-text-editor-minimap::shadow .minimap-visible-area, html atom-text-editor-minimap::shadow .minimap-visible-area => atom-text-editor atom-text-editor-minimap::shadow .minimap-visible-area, atom-text-editor.editor atom-text-editor-minimap::shadow .minimap-visible-area, html atom-text-editor-minimap::shadow .minimap-visible-area

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by arcticicestudio** [comment]
Thanks for your report 👍 

This is related to the change that [elements are no longer encapsulated within a shadow DOM boundary](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) which is a theme package API change announced some weeks ago.
Atom will automatically convert the deprecated selectors so there should be no usage problems, the deprecation warning is a preparation only for package developers so they can update to the new API.

❗️ As soon as the changes of the newer [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-ui) package are merged these changes will be adopted to this package. You can read a more detailed information in [arcticicestudio/nord#49](https://github.com/arcticicestudio/nord-atom-ui/issues/49) of the [Nord Atom UI](https://github.com/arcticicestudio/nord-atom-ui) repository and in [this](https://github.com/arcticicestudio/nord-atom-ui/issues/51#issuecomment-272680263) issue comment related to the same deprecation report. ❗️

**Comment by eadwu** [comment]
Will this be fixed anytime in the future? It seems like this has been done for a few months now on Nord Atom UI.

**Comment by arcticicestudio** [comment]
Sorry for the delay 😞 
I'm busy with the Nord project and the high amount of incoming tickets and port project requests everyday and try to manage to get things done next to my job as developer and my family. I'll create a TODO reminder to merge this as soon possible for all 6 Northem Atom UI- and Syntax projects.

**Comment by arcticicestudio** [comment]
I've created #11 which finally migrates to the new 1.13 theming API 😄 
I'll be merged into the next APM package release version.

**Comment by arcticicestudio** [comment]
🚢 Shipped with APM package release version 🏷 [2.1.0](https://github.com/arcticicestudio/northem-dark-atom-ui/releases/tag/v2.1.0).
